/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asistencias;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rup
 */
public class AsistenciasGUI extends javax.swing.JFrame {
    static Connection conn = new DBConnection().connect();
     /**
     * Creates new form AsistenciasGUI
     */
    public AsistenciasGUI() {
        initComponents();
        checkBecarioDatos.setEnabled(false);
        try {
            SelectNameFromSQL("asistenciasrobot.Alumnos", jComboBoxAlumnos);
            SelectNameFromSQL("asistenciasrobot.Alumnos", comboDatosAlumnos);
            SelectNameFromSQL("asistenciasrobot.Proyectos", jComboBoxProyectos);
        } catch (SQLException ex) {
            Logger.getLogger(AsistenciasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnTomarLista = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnNuevoSemestre = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNombreAlumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkBecarioSi = new javax.swing.JCheckBox();
        btnAgregarAlumno = new javax.swing.JButton();
        jComboBoxAlumnos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarAlumno = new javax.swing.JButton();
        btnAgregarBecario = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comboSemestreAlumnos = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProyectos = new javax.swing.JComboBox();
        btnTerminarProyecto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textNombreProyecto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarProyecto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        comboDatosAlumnos = new javax.swing.JComboBox();
        btnDatosAlumnos = new javax.swing.JButton();
        textHorasDatos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textAsistenciasDatos = new javax.swing.JTextField();
        textFaltasDatos = new javax.swing.JTextField();
        checkBecarioDatos = new javax.swing.JCheckBox();
        textProyectoDatos = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textSemestreDatos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(84, 196, 253));
        setName("frame-menu"); // NOI18N
        setResizable(false);

        jTabbedPane2.setBackground(new java.awt.Color(83, 209, 254));
        jTabbedPane2.setName("tabbedpane_asistencias"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(83, 209, 254));
        jPanel4.setName("tab_lista"); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(83, 209, 254));
        jTextField1.setFont(new java.awt.Font("gargi", 1, 30)); // NOI18N
        jTextField1.setText("Sistema de Asistencias: Robotica");
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setName("text_titulo"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnTomarLista.setFont(new java.awt.Font("Droid Sans", 0, 48)); // NOI18N
        btnTomarLista.setText("Tomar Lista");
        btnTomarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarListaActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnNuevoSemestre.setBackground(new java.awt.Color(0, 255, 214));
        btnNuevoSemestre.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        btnNuevoSemestre.setText("Nuevo Semestre");
        btnNuevoSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoSemestreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btnTomarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(btnNuevoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(btnTomarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnNuevoSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tomar Lista", null, jPanel4, "");

        jPanel5.setBackground(new java.awt.Color(83, 209, 254));
        jPanel5.setAutoscrolls(true);
        jPanel5.setName("tab_alumnos"); // NOI18N

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(83, 209, 254));
        jTextField5.setFont(new java.awt.Font("gargi", 1, 30)); // NOI18N
        jTextField5.setText("Sistema de Asistencias: Robotica");
        jTextField5.setAutoscrolls(false);
        jTextField5.setBorder(null);
        jTextField5.setName("text_titulo2"); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel1.setText("Agregar Alumno");
        jLabel1.setName("labelAgregarAlumnos"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        textNombreAlumno.setName("textNombreAlumno"); // NOI18N
        textNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Becario en Robotica:");
        jLabel3.setName("labelAlumnosBecario"); // NOI18N

        checkBecarioSi.setText("Si");
        checkBecarioSi.setName("checkAlumnosBecario"); // NOI18N
        checkBecarioSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBecarioSiActionPerformed(evt);
            }
        });

        btnAgregarAlumno.setText("Agregar");
        btnAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlumnoActionPerformed(evt);
            }
        });

        jComboBoxAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlumnosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel4.setText("Editar Alumno");

        btnEliminarAlumno.setText("Eliminar");
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });

        btnAgregarBecario.setText("Agregar Becario");
        btnAgregarBecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarBecarioActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel14.setText("Semestre:");

        comboSemestreAlumnos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAgregarAlumno)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarBecario))
                                .addComponent(jComboBoxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(textNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(checkBecarioSi))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(comboSemestreAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(28, 28, 28))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBecarioSi))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAlumno)
                    .addComponent(btnAgregarBecario)
                    .addComponent(jLabel14)
                    .addComponent(comboSemestreAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAgregarAlumno)
                .addGap(102, 102, 102))
        );

        textNombreAlumno.getAccessibleContext().setAccessibleName("textNombreAlumno");
        checkBecarioSi.getAccessibleContext().setAccessibleName("checkAlumnosBecario");

        jTabbedPane2.addTab("Alumnos", jPanel5);

        jPanel6.setBackground(new java.awt.Color(83, 209, 254));
        jPanel6.setName("tab_proyectos"); // NOI18N

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(83, 209, 254));
        jTextField6.setFont(new java.awt.Font("gargi", 1, 30)); // NOI18N
        jTextField6.setText("Sistema de Asistencias: Robotica");
        jTextField6.setAutoscrolls(false);
        jTextField6.setBorder(null);
        jTextField6.setName("text_titulo3"); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N

        jComboBoxProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProyectosActionPerformed(evt);
            }
        });

        btnTerminarProyecto.setText("Terminar");
        btnTerminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarProyectoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");

        textNombreProyecto.setName("textNombreAlumno"); // NOI18N
        textNombreProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreProyectoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel7.setText("Agregar Proyecto");
        jLabel7.setName("labelAgregarAlumnos"); // NOI18N

        btnAgregarProyecto.setText("Agregar");
        btnAgregarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProyectoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel8.setText("Terminar Proyecto");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProyecto)
                .addGap(177, 177, 177))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnTerminarProyecto)
                                .addGap(130, 130, 130))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel8))
                            .addComponent(jComboBoxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap(470, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(textNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)))
                    .addGap(52, 52, 52)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                        .addGap(106, 106, 106)
                        .addComponent(btnAgregarProyecto)
                        .addGap(246, 246, 246))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnTerminarProyecto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(316, 316, 316)))
        );

        jTabbedPane2.addTab("Proyectos", jPanel6);

        jPanel7.setBackground(new java.awt.Color(104, 206, 253));
        jPanel7.setName(""); // NOI18N

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(83, 209, 254));
        jTextField7.setFont(new java.awt.Font("gargi", 1, 30)); // NOI18N
        jTextField7.setText("Sistema de Asistencias: Robotica");
        jTextField7.setAutoscrolls(false);
        jTextField7.setBorder(null);
        jTextField7.setName("text_titulo4"); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btnDatosAlumnos.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        btnDatosAlumnos.setText("Datos");
        btnDatosAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAlumnosActionPerformed(evt);
            }
        });

        textHorasDatos.setEditable(false);

        jLabel9.setText("Total de horas");

        jLabel10.setText("Total de asistencias");

        jLabel11.setText("Total de faltas");

        jLabel12.setText("Becario en robotica");

        jLabel13.setText("Proyecto");

        textAsistenciasDatos.setEditable(false);

        textFaltasDatos.setEditable(false);

        textProyectoDatos.setEditable(false);

        jLabel15.setText("Semestre");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(comboDatosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(btnDatosAlumnos))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAsistenciasDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(textFaltasDatos)
                            .addComponent(textProyectoDatos)
                            .addComponent(textHorasDatos)
                            .addComponent(checkBecarioDatos)
                            .addComponent(textSemestreDatos))))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(comboDatosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatosAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHorasDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textAsistenciasDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textFaltasDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBecarioDatos)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textProyectoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(textSemestreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Datos", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void checkBecarioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBecarioSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBecarioSiActionPerformed

    private void textNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreAlumnoActionPerformed

    private void btnAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        if(textNombreAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insertar Nombre");
        }
        else {
            String sql = "insert into asistenciasrobot.Alumnos " + 
            "(name, totalhoras, totalasistencias, becariorobotica, faltas, proyecto, semestre) values (?, 0.0, 0, ?, 0, ?, ?)";
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, textNombreAlumno.getText());
                ps.setBoolean(2, checkBecarioSi.isSelected());
                ps.setString(3, "");
                ps.setInt(4, Integer.parseInt((String)comboSemestreAlumnos.getSelectedItem()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Agregado");           
            }
            catch (SQLException | HeadlessException e){   

            }
            textNombreAlumno.setText("");
            jComboBoxAlumnos.removeAllItems();
            comboDatosAlumnos.removeAllItems();
            try {
                SelectNameFromSQL("asistenciasrobot.Alumnos", jComboBoxAlumnos);
                SelectNameFromSQL("asistenciasrobot.Alumnos", comboDatosAlumnos);
            } catch (SQLException ex) {
                Logger.getLogger(AsistenciasGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAgregarAlumnoActionPerformed

    private void jComboBoxAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlumnosActionPerformed

    }//GEN-LAST:event_jComboBoxAlumnosActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        String sql = "DELETE FROM asistenciasrobot.Alumnos WHERE name IS NULL OR name=?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, (String)jComboBoxAlumnos.getSelectedItem());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Eliminado");         
        }
        catch (SQLException | HeadlessException e){
            
        }
        //jComboBoxAlumnos.removeItem(jComboBoxAlumnos.getSelectedItem());
        jComboBoxAlumnos.removeAllItems();
        comboDatosAlumnos.removeAllItems();
        try {
            SelectNameFromSQL("asistenciasrobot.Alumnos", jComboBoxAlumnos);
            SelectNameFromSQL("asistenciasrobot.Alumnos", comboDatosAlumnos);
        } catch (SQLException ex) {
            Logger.getLogger(AsistenciasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void jComboBoxProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProyectosActionPerformed

    private void btnTerminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarProyectoActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM asistenciasrobot.Proyectos WHERE name=?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, (String)jComboBoxProyectos.getSelectedItem());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Terminado");
            
        }
        catch (Exception e){
            
        }
        //jComboBoxProyectos.removeItem(jComboBoxProyectos.getSelectedItem());
        jComboBoxProyectos.removeAllItems();
        try {
            SelectNameFromSQL("asistenciasrobot.Proyectos", jComboBoxProyectos);
        } catch (SQLException ex) {
            Logger.getLogger(AsistenciasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTerminarProyectoActionPerformed

    private void textNombreProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreProyectoActionPerformed

    private void btnAgregarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProyectoActionPerformed
        // TODO add your handling code here:
        if(textNombreProyecto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insertar Nombre");
        }
        else{
            String sql = "insert into asistenciasrobot.Proyectos (name) values (?)";
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, textNombreProyecto.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Agregado");
            }
            catch (Exception e){

            }
            jComboBoxProyectos.removeAllItems();
            try {
                SelectNameFromSQL("asistenciasrobot.Proyectos", jComboBoxProyectos);
            } catch (SQLException ex) {
                Logger.getLogger(AsistenciasGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            textNombreProyecto.setText("");
        }
    }//GEN-LAST:event_btnAgregarProyectoActionPerformed

    private void btnTomarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarListaActionPerformed
        FrameTomarLista ftl = new FrameTomarLista();
        ftl.setVisible(true);
    }//GEN-LAST:event_btnTomarListaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnDatosAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAlumnosActionPerformed
        try {
            SelectIntParaTextboxSQL("totalasistencias", textAsistenciasDatos);
            SelectIntParaTextboxSQL("faltas", textFaltasDatos);
            SelectIntParaTextboxSQL("semestre", textSemestreDatos);
            SelectFloatParaTextboxSQL("totalhoras", textHorasDatos);
            SelectStringParaTextboxSQL("proyecto", textProyectoDatos);
            SelectBooleanParaTextboxSQL();
        } catch (SQLException ex) {
            Logger.getLogger(AsistenciasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDatosAlumnosActionPerformed

    private void btnAgregarBecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBecarioActionPerformed
        String sql = "UPDATE asistenciasrobot.Alumnos SET becariorobotica=true WHERE name=?";
        try {
            PreparedStatement ps = AsistenciasGUI.conn.prepareStatement(sql);
            ps.setString(1, (String)comboDatosAlumnos.getSelectedItem());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Becario Agregado");

        }
        catch (Exception e){

        }
    }//GEN-LAST:event_btnAgregarBecarioActionPerformed

    private void btnNuevoSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoSemestreActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Seguro?", "Nuevo Semestre", JOptionPane.YES_NO_OPTION);
        if (option==0){
            String sql = "UPDATE asistenciasrobot.Alumnos SET semestre=semestre+1";
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Nuevo Semestre");         
            }
            catch (SQLException | HeadlessException e){

            }
        }
    }//GEN-LAST:event_btnNuevoSemestreActionPerformed
    
    static void SelectNameFromSQL(String tableName, JComboBox combobox) throws SQLException {
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT name FROM " + tableName + " ORDER BY name ASC");
            while(rs.next()){
                combobox.addItem(rs.getString(1));
            } 
        }finally {
            rs.close();
            stmt.close();
        }
    }
    
    private void SelectIntParaTextboxSQL(String columna, JTextField textfield) throws SQLException {
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT " + columna + " FROM asistenciasrobot.Alumnos WHERE name = '" + (String)comboDatosAlumnos.getSelectedItem() + "'");
             // get the number of rows from the result set
            if(rs.next()){
                textfield.setText(String.valueOf(rs.getInt(1)));
            }   
        }finally {
            rs.close();
            stmt.close();
        }
    }
    
    private void SelectFloatParaTextboxSQL(String columna, JTextField textfield) throws SQLException {
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT " + columna + " FROM asistenciasrobot.Alumnos WHERE name = '" + (String)comboDatosAlumnos.getSelectedItem() + "'");
             // get the number of rows from the result set
            if(rs.next()){
                textfield.setText(String.valueOf(rs.getFloat(1)));
            }   
        }finally {
            rs.close();
            stmt.close();
        }
    }
    
    private void SelectStringParaTextboxSQL(String columna, JTextField textfield) throws SQLException {
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT " + columna + " FROM asistenciasrobot.Alumnos WHERE name = '" + (String)comboDatosAlumnos.getSelectedItem() + "'");
             // get the number of rows from the result set
            if(rs.next()){
                textfield.setText(rs.getString(1));
            }   
        }finally {
            rs.close();
            stmt.close();
        }
    }
    
    private void SelectBooleanParaTextboxSQL() throws SQLException {
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT becariorobotica FROM asistenciasrobot.Alumnos WHERE name = '" + (String)comboDatosAlumnos.getSelectedItem() + "'");
             // get the number of rows from the result set
            if(rs.next()){
                checkBecarioDatos.setEnabled(true);
                checkBecarioDatos.setSelected(rs.getBoolean(1));
            }   checkBecarioDatos.setEnabled(false);
        }finally {
            rs.close();
            stmt.close();
        }
    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenciasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenciasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenciasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenciasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciasGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnAgregarBecario;
    private javax.swing.JButton btnAgregarProyecto;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDatosAlumnos;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnNuevoSemestre;
    private javax.swing.JButton btnTerminarProyecto;
    private javax.swing.JButton btnTomarLista;
    private javax.swing.JCheckBox checkBecarioDatos;
    private javax.swing.JCheckBox checkBecarioSi;
    private javax.swing.JComboBox comboDatosAlumnos;
    private javax.swing.JComboBox comboSemestreAlumnos;
    private javax.swing.JComboBox jComboBoxAlumnos;
    private javax.swing.JComboBox jComboBoxProyectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField textAsistenciasDatos;
    private javax.swing.JTextField textFaltasDatos;
    private javax.swing.JTextField textHorasDatos;
    private javax.swing.JTextField textNombreAlumno;
    private javax.swing.JTextField textNombreProyecto;
    private javax.swing.JTextField textProyectoDatos;
    private javax.swing.JTextField textSemestreDatos;
    // End of variables declaration//GEN-END:variables
}
